# Generated by Django 6.0.3 on 2026-04-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customuser',
            new_name='Customers',
        ),
    ]
