# Generated by Django 6.0.3 on 2026-04-18 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_material_image_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='material',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
